name: talagasari_hub
description: Platform Komunitas Terpadu Desa Talagasari - Informasi Warga & Layanan Jasa Berbasis Lokasi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.0

  # State Management
  get: ^4.6.6

  # Location & GPS
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

  # Image
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.20.2
  flutter_localizations: # ← tambah ini
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/