// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyK8tGY3msYmLOXkXAHoLaIshjpWCxGY8',
    appId: '1:679265812337:web:10ff9504087c89f3dd40d0',
    messagingSenderId: '679265812337',
    projectId: 'talagasari-hub',
    authDomain: 'talagasari-hub.firebaseapp.com',
    storageBucket: 'talagasari-hub.firebasestorage.app',
    measurementId: 'G-0VFCHVX225',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotDk8RrpdnfJT9LSE-2tH0Vo5hhBVpcM',
    appId: '1:679265812337:android:60094b1cb02559f8dd40d0',
    messagingSenderId: '679265812337',
    projectId: 'talagasari-hub',
    storageBucket: 'talagasari-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejZ8s0EmT_lFki2eZ74l7kziIDY7bkH0',
    appId: '1:679265812337:ios:c663fea502100ae0dd40d0',
    messagingSenderId: '679265812337',
    projectId: 'talagasari-hub',
    storageBucket: 'talagasari-hub.firebasestorage.app',
    iosBundleId: 'com.example.talagasariHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejZ8s0EmT_lFki2eZ74l7kziIDY7bkH0',
    appId: '1:679265812337:ios:c663fea502100ae0dd40d0',
    messagingSenderId: '679265812337',
    projectId: 'talagasari-hub',
    storageBucket: 'talagasari-hub.firebasestorage.app',
    iosBundleId: 'com.example.talagasariHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyK8tGY3msYmLOXkXAHoLaIshjpWCxGY8',
    appId: '1:679265812337:web:0a799fa8b50f44e7dd40d0',
    messagingSenderId: '679265812337',
    projectId: 'talagasari-hub',
    authDomain: 'talagasari-hub.firebaseapp.com',
    storageBucket: 'talagasari-hub.firebasestorage.app',
    measurementId: 'G-4Y0G2WF38K',
  );
}
